name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: final/ui  # Указываем рабочую директорию
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: final/ui  # Указываем рабочую директорию
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: final/ui  # Указываем рабочую директорию
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: final/ui/playwright-report/
          retention-days: 30
В каждом шаге я добавил параметр working-directory, который указывает GitHub Actions, в какой директории выполнять команды. Таким образом, все команды будут выполняться внутри директории final/ui, где находится ваш package.json и другие файлы проекта.





